version: "3"

services:

  mongodb_migrate:
    image: mongo:4
    restart: always
    container_name: mongodb_migrate
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: fastfood-db
    ports:
      - '27017:27017'

  # Replica Set (required for Prisma Client)
  mongo:
    build: ./mongodb_replica
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
