version: "3"

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    env_file:
      - ./server/.env
    ports:
      - '3001:3001'
    volumes:
      - ./server:/usr/app/server
      - /usr/app/server/node_modules
    container_name: server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/app/client
      - /usr/app/client/node_modules
    container_name: client

  mongodb_migrate:
    image: mongo:4
    restart: always
    container_name: mongodb_migrate
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: fastfood-db
    ports:
      - '27017:27017'

  # Replica Set (required for Prisma Client)
  mongo:
    build: ./mongodb_replica
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27018
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '27018:27018'

volumes:
  mongo-data:
